### ISSUE TITLE
Not working with OpenCode

### ISSUE THREAD

**Issue by therealmobasha** [cubist38/mlx-openai-server#196]
OpenCode cant properly call any tools when working with MLX-backend based llamas. Getting errors below. Would love to be able to leverage this with OpenCode or a similar agentic flow that automatically calls tools successfully. Please advise
```
mlx logs 8092
INFO:     Waiting for application startup.
2026-02-10 12:21:16 | INFO     | svc.llamas.backends.mlx-openai-server.app.server:setup_server:346 | ✦ Starting server on 0.0.0.0:8092
2026-02-10 12:21:16 | INFO     | svc.llamas.backends.mlx-openai-server.app.main:start:98 | ✦ Server configuration complete.
2026-02-10 12:21:16 | INFO     | svc.llamas.backends.mlx-openai-server.app.main:start:99 | ✦ Starting Uvicorn server...
2026-02-10 12:21:16 | INFO     | svc.llamas.backends.mlx-openai-server.app.server:lifespan:149 | ✦ Initializing MLX handler with model path: mlx-community/MiniMax-M2-4bit
Fetching 37 files: 100%|██████████| 37/37 [00:00<00:00, 63.27it/s]
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8092 (Press CTRL+C to quit)
2026-02-10 12:36:43 | INFO     | svc.llamas.backends.mlx-openai-server.app.handler.mlx_lm:__init__:55 | ✦ Initialized MLXHandler with model path: mlx-community/MiniMax-M2-4bit
2026-02-10 12:36:43 | INFO     | svc.llamas.backends.mlx-openai-server.app.core.queue:start:67 | ✦ Started request queue with max concurrency: 1
2026-02-10 12:36:43 | INFO     | svc.llamas.backends.mlx-openai-server.app.handler.mlx_lm:initialize:86 | ✦ Initialized MLXHandler and started request queue
2026-02-10 12:36:43 | INFO     | svc.llamas.backends.mlx-openai-server.app.server:lifespan:221 | ✦ MLX handler initialized successfully
2026-02-10 12:44:38 | WARNING  | svc.llamas.backends.mlx-openai-server.app.schemas.openai:__log_extra_fields__:42 | ✦ The following fields were present in the request but ignored: {'stream_options'}
INFO:     100.119.213.113:59076 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2026-02-10 12:44:38 | INFO     | svc.llamas.backends.mlx-openai-server.app.handler.mlx_lm:refine_messages:99 | ✦ Filtering out None values from messages...
2026-02-10 12:44:38 | INFO     | svc.llamas.backends.mlx-openai-server.app.handler.mlx_lm:refine_messages:103 | ✦ Messages filtered successfully
2026-02-10 12:44:38 | ERROR    | svc.llamas.backends.mlx-openai-server.app.handler.mlx_lm:generate_text_stream:300 | ✦ Error in text stream generation for request text-0728a603-77c3-40f5-9e6b-9c3ff5597a43: 'str object' has no attribute 'items'
2026-02-10 12:44:38 | ERROR    | svc.llamas.backends.mlx-openai-server.app.api.endpoints:handle_stream_response:582 | ✦ HTTPException in stream wrapper: HTTPException: 500: {'error': {'message': "Failed to generate text stream: 'str object' has no attribute 'items'", 'type': 'server_error', 'param': None, 'code': '500'}}
Traceback (most recent call last):
  File "/Users/USER/svc/llamas/backends/mlx-openai-server/app/handler/mlx_lm.py", line 125, in generate_text_stream
    input_prompt = self.model.create_input_prompt(refined_messages, chat_template_kwargs)
                   │    │     │                   │                 └ {'enable_thinking': True, 'reasoning_effort': 'medium', 'tools': [{'type': 'function', 'function': {'name': 'question', 'desc...
                   │    │     │                   └ [{'content': 'You are opencode, an interactive CLI tool that helps users with software engineering tasks. Use the instruction...
                   │    │     └ <function MLX_LM.create_input_prompt at 0x1798de840>
                   │    └ <mbsvc.llamas.backends.mlx-openai-server.app.models.mlx_lm.MLX_LM object at 0x179ae8110>
                   └ <mbsvc.llamas.backends.mlx-openai-server.app.handler.mlx_lm.MLXLMHandler object at 0x179ae8190>
  File "/Users/USER/svc/llamas/backends/mlx-openai-server/app/models/mlx_lm.py", line 84, in create_input_prompt
    return self.tokenizer.apply_chat_template(
           │    │         └ <function TokenizerWrapper.apply_chat_template at 0x16e331440>
           │    └ <mlx_lm.tokenizer_utils.TokenizerWrapper object at 0x8160c07f50>
           └ <mbsvc.llamas.backends.mlx-openai-server.app.models.mlx_lm.MLX_LM object at 0x179ae8110>
  File "/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/site-packages/mlx_lm/tokenizer_utils.py", line 322, in apply_chat_template
    return self._tokenizer.apply_chat_template(*args, tokenize=tokenize, **kwargs)
           │    │          │                    │              │           └ {'add_generation_prompt': True, 'enable_thinking': True, 'reasoning_effort': 'medium', 'tools': [{'type': 'function', 'functi...
           │    │          │                    │              └ False
           │    │          │                    └ ([{'content': 'You are opencode, an interactive CLI tool that helps users with software engineering tasks. Use the instructio...
           │    │          └ <function PreTrainedTokenizerBase.apply_chat_template at 0x129573ba0>
           │    └ TokenizersBackend(name_or_path='/Users/USER/mnt/llama/mlx/models--mlx-community--MiniMax-M2-4bit/snapshots/fb2e5d39...
           └ <mlx_lm.tokenizer_utils.TokenizerWrapper object at 0x8160c07f50>
  File "/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 3029, in apply_chat_template
    rendered_chat, generation_indices = render_jinja_template(
                                        └ <function render_jinja_template at 0x1291fe340>
  File "/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/site-packages/transformers/utils/chat_template_utils.py", line 537, in render_jinja_template
    rendered_chat = compiled_template.render(
                    │                 └ <function Template.render at 0x1291e9800>
                    └ <Template memory:1799229d0>
  File "/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    │    │           └ <function Environment.handle_exception at 0x1291e9080>
    │    └ <jinja2.sandbox.ImmutableSandboxedEnvironment object at 0x17996dad0>
    └ <Template memory:1799229d0>
  File "/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
          │                              └ None
          └ <function rewrite_traceback_stack at 0x8155b98220>
  File "<template>", line 112, in top-level template code
  File "/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/site-packages/jinja2/sandbox.py", line 399, in call
    if not __self.is_safe_callable(__obj):
  File "/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/site-packages/jinja2/sandbox.py", line 265, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
            │                                         └ Undefined
            └ Undefined
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'items'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/USER/svc/llamas/backends/mlx-openai-server/app/main.py", line 127, in <module>
    main()
    └ <function main at 0x17a54f100>
  File "/Users/USER/svc/llamas/backends/mlx-openai-server/app/main.py", line 123, in main
    cli.main(args=args)
    │   │         └ ['launch', '--model-path', 'mlx-community/MiniMax-M2-4bit', '--port', '8092', '--model-type', 'lm', '--context-length', '8192...
    │   └ <function Command.main at 0x1062182c0>
    └ <Group cli>
  File "/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x104e9b510>
         │    └ <function Group.invoke at 0x1062191c0>
         └ <Group cli>
  File "/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/site-packages/click/core.py", line 1830, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x179b5ff10>
           │               │       │       └ <function Command.invoke at 0x106213f60>
           │               │       └ <Command launch>
           │               └ <click.core.Context object at 0x179b5ff10>
           └ <function Group.invoke.<locals>._process_result at 0x17a54f2e0>
  File "/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'model_path': 'mlx-community/MiniMax-M2-4bit', 'port': 8092, 'model_type': 'lm', 'context_length': 8192, 'max_concurrency': ...
           │   │      │    │           └ <click.core.Context object at 0x179b5ff10>
           │   │      │    └ <function launch at 0x17a51ce00>
           │   │      └ <Command launch>
           │   └ <function Context.invoke at 0x1062131a0>
           └ <click.core.Context object at 0x179b5ff10>
  File "/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'model_path': 'mlx-community/MiniMax-M2-4bit', 'port': 8092, 'model_type': 'lm', 'context_length': 8192, 'max_concurrency': ...
           │         └ ()
           └ <function launch at 0x17a51ce00>
  File "/Users/USER/svc/llamas/backends/mlx-openai-server/app/cli.py", line 266, in launch
    asyncio.run(start(args))
    │       │   │     └ MLXServerConfig(model_path='mlx-community/MiniMax-M2-4bit', model_type='lm', context_length=8192, port=8092, host='0.0.0.0', ...
    │       │   └ <function start at 0x17a54fba0>
    │       └ <function run at 0x105ac6d40>
    └ <module 'asyncio' from '/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/asyncio/__init__.py'>
  File "/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object start at 0x17a57a340>
           │      └ <function Runner.run at 0x105b82e80>
           └ <asyncio.runners.Runner object at 0x179cd36d0>
  File "/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<start() running at /Users/USER/svc/llamas/backends/mlx-openai-server/app/main.p...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x105b80a40>
           │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x179cd36d0>
  File "/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/asyncio/base_events.py", line 641, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x105b809a0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x105b827a0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x105ab40e0>
    └ <Handle Task.task_wakeup(<Future finished result=True>)>
  File "/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=True>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=True>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=True>)>
  File "/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/site-packages/starlette/responses.py", line 266, in wrap
    await func()
          └ functools.partial(<bound method StreamingResponse.stream_response of <starlette.responses.StreamingResponse object at 0x1797c...
  File "/Users/USER/miniconda3/envs/mlx-server/lib/python3.11/site-packages/starlette/responses.py", line 246, in stream_response
    async for chunk in self.body_iterator:
              │        │    └ <async_generator object handle_stream_response at 0x17a525490>
              │        └ <starlette.responses.StreamingResponse object at 0x1797ca010>
              └ b'data: {"id": "chatcmpl_1770745478806008", "choices": [{"delta": {"content": null, "function_call": null, "refusal": null, "...
> File "/Users/USER/svc/llamas/backends/mlx-openai-server/app/api/endpoints.py", line 535, in handle_stream_response
    async for chunk in generator:
                       └ <async_generator object MLXLMHandler.generate_text_stream at 0x8160b05c00>
  File "/Users/USER/svc/llamas/backends/mlx-openai-server/app/handler/mlx_lm.py", line 302, in generate_text_stream
    raise HTTPException(status_code=500, detail=content)
          │                                     └ {'error': {'message': "Failed to generate text stream: 'str object' has no attribute 'items'", 'type': 'server_error', 'param...
          └ <class 'fastapi.exceptions.HTTPException'>
fastapi.exceptions.HTTPException: 500: {'error': {'message': "Failed to generate text stream: 'str object' has no attribute 'items'", 'type': 'server_error', 'param': None, 'code': '500'}}             
```

**Comment by electroheadfx** [comment]
Work with GLM-4.7 and qwen3, qwen3-coder-next, didn't tested with llama

**Comment by therealmobasha** [comment]
It's working now with `MiniMax-M2.1`, however it doesnt effectively call tools. Even though opencode sends all the proper context, the reply is extremely limited, acting more like a chatbot rather than an agent. Using the MiniMaxM2.1 Free Tier however, it is able to effectively act as an agent & work on my codebase (same model in both cases)
```
{
  "message": {
    "id": "msg_c4d9e725200132rwhNQZ3geWJw",
    "sessionID": "ses_3b2618dc5ffeo5cZ4YDAG2tnWF",
    "role": "assistant",
    "time": {
      "created": 1770828755538,
      "completed": 1770828786545
    },
    "parentID": "msg_c4d9e7242001kEUru0mj5oG26e",
    "modelID": "mlx-community/Qwen3-Coder-Next-bf16",
    "providerID": "mlx-8092",
    "mode": "build",
    "agent": "build",
    "path": {
      "cwd": "/Users/USER/code/projects/new-project/flutter-version",
      "root": "/Users/USER/code/projects/new-project/flutter-version"
    },
    "cost": 0,
    "tokens": {
      "input": 10553,
      "output": 243,
      "reasoning": 0,
      "cache": {
        "read": 0,
        "write": 0
      },
      "total": 10796
    },
    "finish": "stop"
  },
  "parts": [
    {
      "id": "prt_c4d9e728b0016cEjkte5YqhIrF",
      "sessionID": "ses_3b2618dc5ffeo5cZ4YDAG2tnWF",
      "messageID": "msg_c4d9e725200132rwhNQZ3geWJw",
      "type": "step-start",
      "snapshot": "9049df63048addc9a78872661a7eeae0bf4acbcf"
    },
    {
      "id": "prt_c4d9ed119001k3IYuqD9hJmZt3",
      "sessionID": "ses_3b2618dc5ffeo5cZ4YDAG2tnWF",
      "messageID": "msg_c4d9e725200132rwhNQZ3geWJw",
      "type": "text",
      "text": "The user wants me to modify the premium star icon throughout the app to a small badge with \"premium\" written in a double bordered yellow box. Let me first explore the codebase to understand its structure and find where premium-related UI elements are defined.\n</think>\n\nI'll help you modify the premium star icon to a small badge with \"premium\" text in a double bordered yellow box. Let me first explore the codebase to understand its structure and find all premium-related UI elements.\n<minimax:tool_call>\n<invoke name=\"task\">\n<parameter name=\"description\">Find premium UI components</parameter>\n<parameter name=\"prompt\">Explore the codebase to find all premium-related UI components, particularly star icons and premium badges. Search for:\n1. Premium icon files (SVG, images)\n2. Premium-related components/widgets\n3. Any existing premium badge implementations\n4. Star icons that might be used for premium indication\n\nReport back with:\n- File paths of all premium-related UI components\n- How the premium star is currently implemented\n- Where these components are used throughout the app\n- The overall structure of the UI components directory</parameter>\n<parameter name=\"subagent_type\">explore</parameter>\n</invoke>\n</minimax:tool_call>",
      "time": {
        "start": 1770828786482,
        "end": 1770828786482
      }
    },
    {
      "id": "prt_c4d9eeb33001LXi2iJyWqbJZNB",
      "sessionID": "ses_3b2618dc5ffeo5cZ4YDAG2tnWF",
      "messageID": "msg_c4d9e725200132rwhNQZ3geWJw",
      "type": "step-finish",
      "reason": "stop",
      "snapshot": "6bccd898c3aee808ad37bc8c8410d6e5947c75f3",
      "cost": 0,
      "tokens": {
        "total": 10796,
        "input": 10553,
        "output": 243,
        "reasoning": 0,
        "cache": {
          "read": 0,
          "write": 0
        }
      }
    },
    {
      "id": "prt_c4d9eeb70001xEJhEISP5nk6Nj",
      "sessionID": "ses_3b2618dc5ffeo5cZ4YDAG2tnWF",
      "messageID": "msg_c4d9e725200132rwhNQZ3geWJw",
      "type": "patch",
      "hash": "9049df63048addc9a78872661a7eeae0bf4acbcf",
      "files": [
        "/Users/USER/code/projects/new-project/flutter-version/lib/screens/devices/devices_screen.dart"
      ]
    }
  ]
}
```

It attempts to call the tool here
```
<minimax:tool_call>\n<invoke name=\"task\">\n<parameter name=\"description\">Find premium UI components</parameter>\n<parameter name=\"prompt\">Explore the codebase to find all premium-related UI components, particularly star icons and premium badges. Search for:\n1. Premium icon files (SVG, images)\n2. Premium-related components/widgets\n3. Any existing premium badge implementations\n4. Star icons that might be used for premium indication\n\nReport back with:\n- File paths of all premium-related UI components\n- How the premium star is currently implemented\n- Where these components are used throughout the app\n- The overall structure of the UI components directory</parameter>\n<parameter name=\"subagent_type\">explore</parameter>\n</invoke>\n</minimax:tool_call>",
```

but then it just stops there

**Comment by cubist38** [comment]
> It's working now with `MiniMax-M2.1` using
> 
> ```
>  /Users/USER/miniconda3/envs/mlx-server/bin/python -m svc.llamas.backends.mlx-openai-server.app.main --model-path mlx-community/MiniMax-M2.1-4bit --port 8092 --max-concurrency 1 --queue-timeout 300 --queue-size 100 --enable-auto-tool-choice
> ```
> 
> However it still doesnt effectively call/utilize tools. Even though opencode sends all the proper context, the reply is extremely limited, acting more like a chatbot rather than an agent.
> 
> ```
> {
>   "message": {
>     "id": "msg_c4d9e725200132rwhNQZ3geWJw",
>     "sessionID": "ses_3b2618dc5ffeo5cZ4YDAG2tnWF",
>     "role": "assistant",
>     "time": {
>       "created": 1770828755538,
>       "completed": 1770828786545
>     },
>     "parentID": "msg_c4d9e7242001kEUru0mj5oG26e",
>     "modelID": "mlx-community/Qwen3-Coder-Next-bf16",
>     "providerID": "mlx-8092",
>     "mode": "build",
>     "agent": "build",
>     "path": {
>       "cwd": "/Users/USER/code/projects/new-project/flutter-version",
>       "root": "/Users/USER/code/projects/new-project/flutter-version"
>     },
>     "cost": 0,
>     "tokens": {
>       "input": 10553,
>       "output": 243,
>       "reasoning": 0,
>       "cache": {
>         "read": 0,
>         "write": 0
>       },
>       "total": 10796
>     },
>     "finish": "stop"
>   },
>   "parts": [
>     {
>       "id": "prt_c4d9e728b0016cEjkte5YqhIrF",
>       "sessionID": "ses_3b2618dc5ffeo5cZ4YDAG2tnWF",
>       "messageID": "msg_c4d9e725200132rwhNQZ3geWJw",
>       "type": "step-start",
>       "snapshot": "9049df63048addc9a78872661a7eeae0bf4acbcf"
>     },
>     {
>       "id": "prt_c4d9ed119001k3IYuqD9hJmZt3",
>       "sessionID": "ses_3b2618dc5ffeo5cZ4YDAG2tnWF",
>       "messageID": "msg_c4d9e725200132rwhNQZ3geWJw",
>       "type": "text",
>       "text": "The user wants me to modify the premium star icon throughout the app to a small badge with \"premium\" written in a double bordered yellow box. Let me first explore the codebase to understand its structure and find where premium-related UI elements are defined.\n</think>\n\nI'll help you modify the premium star icon to a small badge with \"premium\" text in a double bordered yellow box. Let me first explore the codebase to understand its structure and find all premium-related UI elements.\n<minimax:tool_call>\n<invoke name=\"task\">\n<parameter name=\"description\">Find premium UI components</parameter>\n<parameter name=\"prompt\">Explore the codebase to find all premium-related UI components, particularly star icons and premium badges. Search for:\n1. Premium icon files (SVG, images)\n2. Premium-related components/widgets\n3. Any existing premium badge implementations\n4. Star icons that might be used for premium indication\n\nReport back with:\n- File paths of all premium-related UI components\n- How the premium star is currently implemented\n- Where these components are used throughout the app\n- The overall structure of the UI components directory</parameter>\n<parameter name=\"subagent_type\">explore</parameter>\n</invoke>\n</minimax:tool_call>",
>       "time": {
>         "start": 1770828786482,
>         "end": 1770828786482
>       }
>     },
>     {
>       "id": "prt_c4d9eeb33001LXi2iJyWqbJZNB",
>       "sessionID": "ses_3b2618dc5ffeo5cZ4YDAG2tnWF",
>       "messageID": "msg_c4d9e725200132rwhNQZ3geWJw",
>       "type": "step-finish",
>       "reason": "stop",
>       "snapshot": "6bccd898c3aee808ad37bc8c8410d6e5947c75f3",
>       "cost": 0,
>       "tokens": {
>         "total": 10796,
>         "input": 10553,
>         "output": 243,
>         "reasoning": 0,
>         "cache": {
>           "read": 0,
>           "write": 0
>         }
>       }
>     },
>     {
>       "id": "prt_c4d9eeb70001xEJhEISP5nk6Nj",
>       "sessionID": "ses_3b2618dc5ffeo5cZ4YDAG2tnWF",
>       "messageID": "msg_c4d9e725200132rwhNQZ3geWJw",
>       "type": "patch",
>       "hash": "9049df63048addc9a78872661a7eeae0bf4acbcf",
>       "files": [
>         "/Users/USER/code/projects/new-project/flutter-version/lib/screens/devices/devices_screen.dart"
>       ]
>     }
>   ]
> }
> ```
> 
> It attempts to call the tool here
> 
> ```
> <minimax:tool_call>\n<invoke name=\"task\">\n<parameter name=\"description\">Find premium UI components</parameter>\n<parameter name=\"prompt\">Explore the codebase to find all premium-related UI components, particularly star icons and premium badges. Search for:\n1. Premium icon files (SVG, images)\n2. Premium-related components/widgets\n3. Any existing premium badge implementations\n4. Star icons that might be used for premium indication\n\nReport back with:\n- File paths of all premium-related UI components\n- How the premium star is currently implemented\n- Where these components are used throughout the app\n- The overall structure of the UI components directory</parameter>\n<parameter name=\"subagent_type\">explore</parameter>\n</invoke>\n</minimax:tool_call>",
> ```
> 
> but then it just stops there.
> 
> Using the MiniMaxM2.1 Free Tier however, it is able to effectively act as an agent & work on my codebase

Hey @therealmobasha, the correct command to launch `MiniMax-M2.1` with the appropriate tool call parsers is:

```bash
mlx-openai-server launch \
  --model-path mlx-community/MiniMax-M2.1-4bit \
  --port 8092 \
  --reasoning-parser minimax_m2 \
  --tool-call-parser minimax_m2 \
  --message-converter minimax_m2
```
Could you please try launching it with this command and let me know if it works on your side?
